version: "3.4"

services:
  api:
    build: ./bee_build
    image: ${SERVICE_NAME}
    container_name: ${SERVICE_NAME}
    volumes:
      - gosrc:/go
      - .:/go/src/${API_BASE_DIR}/${API_NAME}
    env_file: 
      - .env
    ports:
      - "${PORT}:${PORT}"
    command: sh -c 'cd ${API_BASE_DIR}/${API_NAME};go get -v -u ./...; bee run -downdoc=true -gendoc=true'
    networks:
      - back_end
volumes:
  gosrc:
networks:
  back_end:
    external: true
